### ISSUE TITLE
Firefox Compatible

### ISSUE THREAD

**Issue by benjaminpwarren** [monting/Tab-Extract#1]
FYI, this extension is compatible with Firefox (since at least v57), you just need to add
```
"browser_action": {
    "default_icon": {
      "16": "icon_016.png",
      "32": "icon_032.png",
      "48": "icon_048.png",
      "128": "icon_128.png"
    }
  },  
```
to `manifest.json` to give it an icon (leave the existing `"icons"` block, Chrome seems to use it for its Extensions page).

Note: In Firefox, you have to type `'ex' + space` to trigger -- tab won't work.

It would be great if you could publish on https://addons.mozilla.org/.

p.s. other web extension compatible browsers might also work.
p.p.s. Love this extension, it's so useful!

**Comment by edjroot** [comment]
Since it looks like this project is no longer maintained, I've just forked and published it myself (but feel free to request removal):

https://addons.mozilla.org/en-GB/firefox/addon/tabextract/

**Comment by monting** [comment]
@benjaminpwarren just saw this, after writing a new version for FF, and pushing it live:

https://addons.mozilla.org/en-US/firefox/addon/tab-extract-port/

Had no idea that it was compatible - oh well, code could use a cleanup anyway!

Thanks for the tip on the `tab` key not working, I'll change the description 👌
