### ISSUE TITLE
Misses sleeping tabs (chrome)

### ISSUE THREAD

**Issue by eric2** [monting/Tab-Extract#3]
Only recently active tabs are extracted (observed in Chrome 115).  Presumably the data structure being searched once included all tabs but must have changed to only include recent or non-sleeping tabs.  I hope there's still a way to extract from the set of all tabs.

**Comment by eric2** [comment]
This was also reported in the chrome webstore review by user "Google Store" on Apr 10, 2023

**Comment by eric2** [comment]
This was also reported in the chrome webstore review by user "Google Store" on Apr 10, 2023.  (I inadvertently closed as I was trying to add this comment so re-opened.)

**Comment by eric2** [comment]
This was also reported in the chrome webstore review by user "Google Store" on Apr 10, 2023. (I inadvertently closed as I was trying to add this comment so trying to re-open.)

**Comment by aeimi** [comment]
But issue still exist, right? Suspended tabs are not included while extracting.
